general:
  seed: 1
dataset:
  default_dir: ./dataset
  type: collect
  path: GridWorld_ch3_32x32_5760_salt0.05_pepper0.05.pt
  collect_config:
    dataset_size: 5760
    type: custom
    env_name: GridWorld
    custom_args:
      env_init_args:
        env_mode: 1
        no_wall: true
        no_door: true
        no_key: true
        simple_image: false
        noise:
          handle_fn: add_salt_pepper_noise
          args:
            density: 0.1
    env_config:
      image_size: !!python/tuple [3, 32, 32]
  load_config:
    batch_size: 32
    division:
      - 0.7
      - 0.3
    shuffle: true
model:
  model_name: ConvJointVAE
  model_args:
    temp: 0.67
    latent_disc:
      - 16
    disc_capacity: !!python/tuple [0., 4, 5.0e-4, 100]
    cont_capacity: null
    input_size: !!python/tuple [3, 32, 32]
    kernel_sizes:
      - 32
      - 64
      - 64
    hidden_size: 256
    dim_z: 16
    binary: true
train:
  epochs: 100
  cuda: false
  log_interval: 10
  optimizer_config:
    lr: 1.0e-3
  save_config:
    default_dir: ./checkpoints
    path: GridWorld_ch3_32x32_5760/NoiseTest3-ConvJointVAE_epoch100_c16_temp0.67.pth.tar
    store_cfgs:
      - general
      - dataset
      - model
      - train
test:
  save_config:
    default_dir: ./results/GridWorld_ch3_32x32_5760/ConvJointVAE/NoiseTest3-epoch100_c16_temp0.67
    tag: epoch100_c16_temp0.67
